public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        byte apple = 60;
        System.out.println("Значение переменной apple с типом byte равно " + apple);
        int car = 1200000;
        System.out.println("Значение переменной car с типом int равно " + car);
        short cat = 333;
        System.out.println("Значение переменной cat с типом short равно " + cat);
        long dog = 2000000;
        System.out.println("Значение переменной dog с типом long равно " + dog);
        float litres = 1.1F;
        System.out.println("Значение переменной litres с типом float равно " + litres);
        double kg = 15.1;
        System.out.println("Значение переменной kg с типом double равно " + kg);
        double a = 27.12;
        System.out.println(a);
        long b = 987678965549L;
        System.out.println(b);
        float c = 2.786f;
        System.out.println(c);
        short d = 569;
        System.out.println(d);
        short f = -159;
        System.out.println(f);
        short e = 27897;
        System.out.println(e);
        byte j = 67;
        System.out.println(j);
        byte LP = 23;
        byte AS = 27;
        byte EA = 30;
        short paper = 480;
        int sheetOnStudent = paper/(LP+AS+EA);
        System.out.println("На каждого ученика рассчитано " + sheetOnStudent + " листов бумаги");
        byte bottle = 16;
        byte minuts = 2;
        int bottleOnOneMinutes = bottle / minuts;
        int bottleOn20 = bottleOnOneMinutes*20;
        System.out.println("За 20 минут машина произвела  " + bottleOn20 + " штук бутылок");
        int bottleInDay = bottleOnOneMinutes*60*24;
        System.out.println("За сутки машина произвела  " + bottleInDay + " штук бутылок");
        int bottleInThreeDay = bottleInDay*3;
        System.out.println("За 3 дня машина произвела  " + bottleInThreeDay + " штук бутылок");
        int bottleInMonth = bottleInDay*30;
        System.out.println("За 1 месяц машина произвела  " + bottleInMonth + " штук бутылок");
        byte allPot = 120;
        byte whitePaint = 2;
        byte brownPaint = 4;
        int allClasses = allPot/(whitePaint+brownPaint);
        int whitePaintinAllClass = (short) (whitePaint*allClasses);
        int brownPaintinAllClass = (short) (brownPaint*allClasses);
        System.out.println("В школе, где " + allClasses + " классов, нужно " + whitePaintinAllClass + " банок белой краски и " + brownPaintinAllClass + " банок коричневой краски");
        byte oneBananasGr = 80;
        byte Milk100Gr = 105;
        byte iceCreamGr = 100;
        byte boolsGr = 70;
        int receptGr = (oneBananasGr*5)+(Milk100Gr*2)+(iceCreamGr*20)+(boolsGr*4);
        System.out.println(receptGr);
        int grPerKg = 1000;
        float receptKg = receptGr/(float)grPerKg;
        System.out.println(receptKg);
        int kgResault = 7;
        int resultGr = kgResault*1000;
        int loss1Gr = 250;
        int loss2Gr = 500;
        int resaltDay250 = resultGr/loss1Gr;
        System.out.println(resaltDay250);
        int resaltDay500 = resultGr/loss2Gr;
        System.out.println(resaltDay500);
        int MashaInMonth = 67760;
        int DenisInMonth = 83690;
        int KristinaInMonth = 76230;
        float MashaTenPer = (float) (MashaInMonth*0.10);
        float DenisTenPer = (float) (DenisInMonth*0.10);
        float KristinaTenPer = (float) (KristinaInMonth*0.10);
        int MashaMonthAfter = (int) (MashaInMonth+MashaTenPer);
        int DenisMonthAfter = (int) (DenisInMonth+DenisTenPer);
        int KristinaMonthAfter = (int) (KristinaInMonth+KristinaTenPer);
        int MashaBefAft = (MashaMonthAfter*12)-(MashaInMonth*12);
        int DenisBerAft = (DenisMonthAfter*12)-(DenisInMonth*12);
        int KristinaBerAft = (KristinaMonthAfter*12)-(KristinaInMonth*12);
        System.out.println("Маша теперь получает " + MashaMonthAfter + " рублей. Годовой доход вырос на " + MashaBefAft + " рублей");
        System.out.println("Денис теперь получает " + DenisMonthAfter + " рублей. Годовой доход вырос на " + DenisBerAft + " рублей");
        System.out.println("Кристина теперь получает " + KristinaMonthAfter + " рублей. Годовой доход вырос на " + KristinaBerAft + " рублей");

    }
}